// this is an input file for the "REST Client" (similar to postman) VsCode extension:

//login successful request
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "john",
    "password": "1234"
}

### // this is how to delimit requests
// failing login request
POST http://localhost:8080/login
Content-Type: application/json

{
    "username": "john2",
    "password": "1234"
}

### For any query below run login successful request above, then navigate to 
# /home/edwin/work/typescriptANDnodeJsCourse/ManagerServer/database/Tokens.db
# to see the valid `tokenId`

### getting user by id
GET http://localhost:8080/users?id=testisfddd
Authorization: puppy9w68a

### getting user by name
GET http://localhost:8080/users?name=j
Authorization: puppy9w68a

### adding a user to db
PUT http://localhost:8080/users
Authorization: zc08ttutu7
Content-Type: application/json

{
    "age": 45,
    "email": "some@sillyemail.com",
    "name": "john",
    "workingPosition": 3
}

### deleting user by id
DELETE http://localhost:8080/users?id=testdelete3
Authorization: puppy9w68a
